# Project: Project5
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Time.o
LINKOBJ  = main.o Time.o
LIBS     = -L"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/lib" -L"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/include" -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/include" -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/mywork/KBTCProgramming/allmylife/C++/2892019/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project5.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Time.o: Time.cpp
	$(CPP) -c Time.cpp -o Time.o $(CXXFLAGS)
